services:
  db:
    container_name: citizen_link_db
    image: pgvector/pgvector:0.8.1-pg18-trixie
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      # note: pgvector's official image uses the default Postgres data directory but within the container hence data is lost on container restart unless mapped to a volume. The following line maps the named volume 'db_data' to the internal Postgres data folder.
      # - db_data:/pgvector/pgvector
      # This maps the named volume 'db_data' to the internal Postgres data folder
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # Best practice: ensures the DB uses the exact volume path
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    container_name: citizen_link_redis
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      sh -c "
        echo 'user default off' > /tmp/redis.acl &&
        echo \"user $${REDIS_USERNAME} on >$${REDIS_PASSWORD} ~* &* +@all\" >> /tmp/redis.acl &&
        redis-server --aclfile /tmp/redis.acl
      "
    ports:
      - '6379:6379'
    env_file:
      - .env
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -u redis://$${REDIS_USERNAME}:$${REDIS_PASSWORD}@localhost:6379 ping | grep -q PONG']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  minio:
    container_name: citizen_link_minio
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001" # Minio needs a command to start
    ports:
      - '9000:9000' # API
      - '9001:9001' # Console UI
    env_file:
      - .env
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9000/minio/health/live']
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - '8025:8025' # Web UI & API
      - '1025:1025' # SMTP server
    healthcheck:
      test: ["CMD", "/mailpit", "readyz"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: citizen_link_app
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    ports:
      - '2000:2000'
    env_file:
      - .env
    environment:
      # App Config
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      # Database Config
      - DATABASE_URL=${DATABASE_URL}
      # Redis Config
      - REDIS_DB_URL=${REDIS_DB_URL}
      # Better Auth Config
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      # Admin user and seed config
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SKIP_ADMIN_IF_EXISTS=${SKIP_ADMIN_IF_EXISTS}
      # S3 Config
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRETE_ACCESS_KEY_ID=${S3_SECRETE_ACCESS_KEY_ID}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET_TMP=${S3_BUCKET_TMP}
      - S3_BUCKET_CASES=${S3_BUCKET_CASES}
      - S3_MAX_FILE_SIZE=${S3_MAX_FILE_SIZE}
      # SMTP / Email Config
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_FROM=${SMTP_FROM}
      # Expo Push Config
      - EXPO_ACCESS_TOKEN=${EXPO_ACCESS_TOKEN}
      # Embedding Config
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - EMBEDDING_BASE_URL=${EMBEDDING_BASE_URL}
      - EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
      - EMBEDDING_IS_OPENAI=${EMBEDDING_IS_OPENAI}
      # OpenAI Config
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}
      # Vision AI Config
      - VISION_AI_BASE_URL=${VISION_AI_BASE_URL}
      - VISION_AI_MODEL=${VISION_AI_MODEL}
      - VISION_AI_API_KEY=${VISION_AI_API_KEY}
      # Text Extraction AI Config
      - TEXT_EXTRACTION_AI_BASE_URL=${TEXT_EXTRACTION_AI_BASE_URL}
      - TEXT_EXTRACTION_AI_MODEL=${TEXT_EXTRACTION_AI_MODEL}
      - TEXT_EXTRACTION_AI_API_KEY=${TEXT_EXTRACTION_AI_API_KEY}
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:2000/api || exit 1']
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
