export enum EntityPrefix {
  TEST = 'TST',
  MATCH = 'MTH',
  CLAIM = 'CLM',
  EXCHANGE = 'EXC',
  INVOICE = 'INV',
  TRANSACTION = 'TRX',
  DISBURSEMENT = 'DSB',
  WITHDRAWAL = 'WDR',
  DISPUTE = 'DSP',
  DOCUMENT = 'DOC',
  LOST_DOCUMENT_CASE = 'LDC',
  FOUND_DOCUMENT_CASE = 'FDC',
  MAUZO_PAYMENT_INTENT = 'MPI',
}

export const HUMAN_ID_OPTIONS = 'HUMAN_ID_OPTIONS';
