import { createAccessControl } from 'better-auth/plugins/access';
import {
  adminAc,
  userAc,
  defaultStatements as defaultAdminStatements,
  defaultRoles as adminDefaultRoles,
} from 'better-auth/plugins/admin/access';

export const adminPluginAcl = createAccessControl({
  ...defaultAdminStatements,
  documentType: ['create', 'update', 'delete', 'restore'],
  addressLocale: ['create', 'update', 'delete', 'restore'],
  addressHierarchy: ['create', 'update', 'delete', 'restore'],
  station: ['create', 'update', 'delete', 'restore'],
  documentCase: [
    'list-any',
    'view-any',
    'verify',
    'reject',
    'update',
    'delete',
    'collect',
  ],
  match: [
    'list-any',
    'create',
    'update',
    'delete',
    'restore',
    'verify',
    'query-case-matches',
  ],
  claim: ['list-any', 'verify', 'reject', 'delete', 'review-dispute'],
  extraction: ['debug'],
  templates: ['create', 'update', 'delete', 'restore'],
  notification: ['list-any', 'view-any', 'manage-any', 'delete', 'test'],
  transitionReason: ['create', 'update', 'delete', 'restore'],
  statusTransition: ['view'],
  documentOperation: ['manage', 'approve', 'reject'],
  documentOperationType: ['manage'],
  stationOperationType: ['manage'],
  staffOperationScope: ['view', 'manage'],
  wallet: ['view-any'],
  address: ['view-any'],
  transaction: ['list-any'],
  disbursement: ['list-any', 'view-any'],
  invoice: ['list-any'],
  setting: ['view-any', 'manage-system'],
  pushToken: ['list-any'],
  handover: ['manage-any'],
  docai: ['view-jobs', 'view-stages', 'view-conversations', 'view-webhooks'],
});

const adminRole = adminPluginAcl.newRole({
  documentType: ['create', 'update', 'delete', 'restore'],
  addressLocale: ['create', 'update', 'delete', 'restore'],
  addressHierarchy: ['create', 'update', 'delete', 'restore'],
  station: ['create', 'update', 'delete', 'restore'],
  documentCase: [
    'list-any',
    'view-any',
    'verify',
    'reject',
    'update',
    'delete',
    'collect',
  ],
  match: [
    'list-any',
    'create',
    'update',
    'delete',
    'restore',
    'verify',
    'query-case-matches',
  ],
  claim: ['list-any', 'verify', 'reject', 'delete', 'review-dispute'],
  extraction: ['debug'],
  templates: ['create', 'update', 'delete', 'restore'],
  notification: ['list-any', 'view-any', 'manage-any', 'delete', 'test'],
  transitionReason: ['create', 'update', 'delete', 'restore'],
  statusTransition: ['view'],
  documentOperation: ['manage', 'approve', 'reject'],
  documentOperationType: ['manage'],
  stationOperationType: ['manage'],
  staffOperationScope: ['view', 'manage'],
  wallet: ['view-any'],
  address: ['view-any'],
  transaction: ['list-any'],
  disbursement: ['list-any', 'view-any'],
  invoice: ['list-any'],
  setting: ['view-any', 'manage-system'],
  pushToken: ['list-any'],
  handover: ['manage-any'],
  docai: ['view-jobs', 'view-stages', 'view-conversations', 'view-webhooks'],
  ...adminAc.statements,
});

const userRole = adminPluginAcl.newRole({
  documentType: [],
  addressLocale: [],
  ...userAc.statements,
});

export const adminPluginRoles = {
  ...adminDefaultRoles,
  admin: adminRole,
  user: userRole,
};
